server:
  port: 8083
spring.application.name: match-stats-service

com:
  ka:
    livescore:
      api-name: LiveScoreAPI
      api-url: https://livescore-football.p.rapidapi.com/soccer
      token: #insert your own token here
      host: livescore-football.p.rapidapi.com
